#!/bin/sh
#
#        +----------------------------------------------------------+
#        | +------------------------------------------------------+ |
#        | |  Quafios init script.                                | |
#        | +------------------------------------------------------+ |
#        +----------------------------------------------------------+
#
# This file is part of Quafios 2.0.1 source code.
# Copyright (C) 2015  Mostafa Abd El-Aziz Mohamed.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Quafios.  If not, see <http://www.gnu.org/licenses/>.
#
# Visit http://www.quafios.com/ for contact information.
#

# inform the user that /bin/init has taken control
echo Quafios init script has taken control... Welcome to Quafios!

# mount filesystems
mount /dev devfs
mount /sys sysfs

# run udev
udev

# run winman
winman &

# change to home directory
cd /home

# run rash on vtty1
rash
