#!/bin/sh

set -e
rm -rf /tmp/quafios-1.0.2 /tmp/quafios-1.0.2.tar.gz
cp -rp /home/iocoder/Projects/Quafios /tmp/quafios-1.0.2
cd /tmp/quafios-1.0.2
rm -rf doc
if [ -a Makefile ]; then
	make distclean
fi
rm -rf autom4te.cache/
cd ..
tar -zcf /tmp/quafios-1.0.2.tar.gz quafios-1.0.2/
