#!/bin/sh

set -ex
rm -rf /tmp/quafios-2.0.1 /tmp/quafios-2.0.1.tar.gz
cp -rp /home/iocoder/Projects/quafios /tmp/quafios-2.0.1
cd /tmp/quafios-2.0.1
rm -rf build
rm -rf .git
if [ -a Makefile ]; then
	make distclean
fi
rm -rf autom4te.cache/
cd ..
tar -zcf /tmp/quafios-2.0.1.tar.gz quafios-2.0.1/
